apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: plugin-webp-se-cloud
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: WebP Cloud Services
    website: https://webp.se/
  logo: logo.svg
  homepage: https://webp.se/
  displayName: "WebP Cloud Services"
  description: "接入 webp.se 平台，实现无入侵的 WebP 图片格式转换"
  configMapName: plugin-webp-se-cloud-configmap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/webp-sh/halo-plugin-webp-cloud/blob/master/LICENSE"
